import { useState } from 'react';
import { db } from '../lib/db';
import { AppSettings, MONTH_NAMES, MONTH_NAMES_RUS, MONTH_NAMES_GR } from '../constants';
import { formatMoney } from '../lib/utils';

interface UseDataExportProps {
  settings: AppSettings;
  curSym: string;
  viewDate: Date;
  calcEarnings: (hours: number) => number;
  addToast: (msg: string, type?: 'info' | 'success' | 'error' | 'warning') => void;
  haptic: (pattern?: number | number[]) => void;
}

export const useDataExport = ({
  settings, curSym, viewDate, calcEarnings, addToast, haptic
}: UseDataExportProps) => {
  const [isExporting, setIsExporting] = useState(false);

  const exportCSV = async () => {
    const allEntries = await db.getAllEntries();
    const rows = [['Date', 'Hours', 'Earned']];
    allEntries.forEach(e => rows.push([e.date, e.hours.toString(), formatMoney(calcEarnings(e.hours))]));
    const csv = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'work-tracker.csv'; a.click();
    addToast('CSV Exported', 'success');
  };

  const exportTXT = async () => {
    const allEntries = await db.getAllEntries();
    
    let totalH = 0;
    let totalE = 0;
    allEntries.forEach(e => {
      totalH += e.hours;
      totalE += calcEarnings(e.hours);
    });

    const mNames = settings.language === 'RUS' ? MONTH_NAMES_RUS : settings.language === 'GR' ? MONTH_NAMES_GR : MONTH_NAMES;
    const currentMonthName = mNames[viewDate.getMonth()];

    let txt = `╔══════════════════════════════════════╗\n`;
    txt += `║        WORK TRACKER — REPORT         ║\n`;
    txt += `╚══════════════════════════════════════╝\n\n`;
    txt += `[USER]:     Professional\n`;
    txt += `[RATE]:     ${curSym}${settings.rate}/h\n`;
    txt += `[OVERTIME]: ${curSym}${settings.overtime}/h\n`;
    txt += `[PERIOD]:   ${currentMonthName} ${viewDate.getFullYear()}\n\n`;
    txt += `────────── PERFORMANCE ──────────\n`;
    txt += `[HOURS]:    ${totalH}h\n`;
    txt += `[EARNED]:   ${curSym}${formatMoney(totalE)}\n\n`;

    allEntries.sort((a,b) => b.date.localeCompare(a.date)).forEach(e => {
      txt += `──────────────────────────────────────\n`;
      txt += `[DATE]:     ${e.date}\n`;
      txt += `[STATUS]:   Work Day\n`;
      txt += `[HOURS]:    ${e.hours}h\n`;
      txt += `[EARNED]:   ${curSym}${formatMoney(calcEarnings(e.hours))}\n`;
    });
    
    txt += `\n══════════════════════════════════════\n`;
    txt += `Создано Work Tracker Pro\n`;

    const blob = new Blob([txt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'work-tracker-report.txt'; a.click();
    addToast('TXT Exported', 'success');
  };

  const shareToTelegram = async (format: 'summary' | 'txt' | 'csv' | 'json' | 'pdf' = 'summary') => {
    if (settings.strictOfflineMode) {
      addToast('Blocked by paranoia mode', 'error');
      return;
    }
    
    try {
      const allEntries = await db.getAllEntries();
      let file: File | null = null;
      let textContent = '';

      if (format === 'summary') {
        const totalHours = allEntries.reduce((acc, curr) => acc + curr.hours, 0);
        const totalEarned = allEntries.reduce((acc, curr) => acc + calcEarnings(curr.hours), 0);
        textContent = `*Work Tracker Report*\n*Total Hours*: ${totalHours}h\n*Total Earned*: ${curSym}${formatMoney(totalEarned)}\n_Generated by Work Tracker Pro_`;
      } else if (format === 'pdf') {
        addToast('Preparing PDF...', 'info');
        const pdfFile = await exportPDF('6months', true);
        if (pdfFile) file = pdfFile;
      } else if (format === 'txt') {
        let totalH = 0;
        let totalE = 0;
        allEntries.forEach(e => {
          totalH += e.hours;
          totalE += calcEarnings(e.hours);
        });
        const mNames = settings.language === 'RUS' ? MONTH_NAMES_RUS : settings.language === 'GR' ? MONTH_NAMES_GR : MONTH_NAMES;
        const currentMonthName = mNames[viewDate.getMonth()];
        let txt = `╔══════════════════════════════════════╗\n`;
        txt += `║        WORK TRACKER — REPORT         ║\n`;
        txt += `╚══════════════════════════════════════╝\n\n`;
        txt += `[USER]:     Professional\n`;
        txt += `[RATE]:     ${curSym}${settings.rate}/h\n`;
        txt += `[OVERTIME]: ${curSym}${settings.overtime}/h\n`;
        txt += `[PERIOD]:   ${currentMonthName} ${viewDate.getFullYear()}\n\n`;
        txt += `────────── PERFORMANCE ──────────\n`;
        txt += `[HOURS]:    ${totalH}h\n`;
        txt += `[EARNED]:   ${curSym}${formatMoney(totalE)}\n\n`;
        allEntries.sort((a,b) => b.date.localeCompare(a.date)).forEach(e => {
          txt += `──────────────────────────────────────\n`;
          txt += `[DATE]:     ${e.date}\n`;
          txt += `[STATUS]:   Work Day\n`;
          txt += `[HOURS]:    ${e.hours}h\n`;
          txt += `[EARNED]:   ${curSym}${formatMoney(calcEarnings(e.hours))}\n`;
        });
        txt += `\n══════════════════════════════════════\n`;
        txt += `Создано Work Tracker Pro\n`;
        const blob = new Blob([txt], { type: 'text/plain' });
        file = new File([blob], 'work-tracker-report.txt', { type: 'text/plain' });
      } else if (format === 'csv') {
        const rows = [['Date', 'Hours', 'Earned']];
        allEntries.forEach(e => rows.push([e.date, e.hours.toString(), formatMoney(calcEarnings(e.hours))]));
        const csv = rows.map(r => r.join(',')).join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        file = new File([blob], 'work-tracker.csv', { type: 'text/csv' });
      } else if (format === 'json') {
        const data = { entries: allEntries, settings };
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        file = new File([blob], 'work-tracker-backup.json', { type: 'application/json' });
      }

      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

      if (format === 'summary') {
        const encodedText = encodeURIComponent(textContent);
        window.open(`https://t.me/share/url?url=${encodedText}`, '_blank');
        addToast('Opened Telegram', 'success');
      } else if (file && isMobile && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'Work Tracker Data',
        });
        addToast('Shared successfully', 'success');
      } else if (file) {
        const url = URL.createObjectURL(file as Blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = file.name;
        a.click();
        addToast('File downloaded', 'success');
      }
    } catch (e: any) {
      if (e.name !== 'AbortError') {
        addToast('Sharing failed', 'error');
        console.error(e);
      }
    }
  };

  const exportICS = async () => {
    const allEntries = await db.getAllEntries();
    
    let ics = `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Work Tracker Pro//EN\nCALSCALE:GREGORIAN\n`;
    
    allEntries.forEach((e, idx) => {
      const d = new Date(e.date);
      const start = e.date.replace(/-/g, '');
      d.setDate(d.getDate() + 1);
      const end = d.toISOString().split('T')[0].replace(/-/g, '');
      const earned = formatMoney(calcEarnings(e.hours));
      
      ics += `BEGIN:VEVENT\n`;
      ics += `UID:shift-${e.date}-${idx}@worktracker.app\n`;
      ics += `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z\n`;
      ics += `SUMMARY:Work (${e.hours}h)\n`;
      ics += `DTSTART;VALUE=DATE:${start}\n`;
      ics += `DTEND;VALUE=DATE:${end}\n`;
      ics += `DESCRIPTION:Worked ${e.hours}h\\nEarned: ${curSym}${earned}\n`;
      ics += `END:VEVENT\n`;
    });
    
    ics += `END:VCALENDAR`;
    
    const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; 
    a.download = 'work-shifts.ics'; 
    a.click();
    addToast('Calendar (.ics) Exported', 'success');
  };

  const shareBackup = async () => {
    const allEntries = await db.getAllEntries();
    const data = { entries: allEntries, settings };
    const blob = new Blob([JSON.stringify(data)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'work-tracker-backup.json'; a.click();
    addToast('Backup Downloaded', 'success');
  };

  const exportPDF = async (period: '6months' | 'year', returnFile = false): Promise<File | undefined> => {
    if (isExporting && !returnFile) return;
    if (!returnFile) {
      setIsExporting(true);
      haptic(30);
      addToast('Loading PDF engine...', 'info');
    }

    try {
      const { jsPDF } = await import("jspdf");
      const autoTableModule = await import("jspdf-autotable");
      const autoTable = (autoTableModule.default || autoTableModule) as any;

      if (!returnFile) addToast('Generating PDF Report...', 'info');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const now = new Date();
      const { normal, goal } = settings;

      const allEntries = await db.getAllEntries();
      let months: { month: number; year: number }[] = [];

      if (period === '6months') {
        for (let i = 5; i >= 0; i--) {
          let mo = viewDate.getMonth() - i, yr = viewDate.getFullYear();
          while (mo < 0) { mo += 12; yr--; }
          months.push({ month: mo, year: yr });
        }
      } else {
        for (let mo = 0; mo < 12; mo++) months.push({ month: mo, year: viewDate.getFullYear() });
      }

      const stats = months.map(({ month, year }) => {
        const ms = `${year}-${String(month + 1).padStart(2, '0')}`;
        const entries = allEntries.filter(e => e.date.startsWith(ms));
        const hours = entries.reduce((s, e) => s + e.hours, 0);
        const earned = entries.reduce((s, e) => s + calcEarnings(e.hours), 0);
        const otHours = entries.reduce((s, e) => s + Math.max(0, e.hours - normal), 0);
        const days = entries.length;
        const pct = goal > 0 ? Math.round((earned / goal) * 100) : 0;
        
        const mNames = settings.language === 'RUS' ? MONTH_NAMES_RUS : settings.language === 'GR' ? MONTH_NAMES_GR : MONTH_NAMES;
        return { label: `${mNames[month].slice(0, 3)} ${year}`, month, year, hours, earned, otHours, days, pct, entries };
      });

      const totalEarned = stats.reduce((s, m) => s + m.earned, 0);
      const totalHours = stats.reduce((s, m) => s + m.hours, 0);
      const totalDays = stats.reduce((s, m) => s + m.days, 0);

      const C = {
        bg: [13, 15, 20],
        card: [20, 20, 24],
        gold: [200, 181, 96],
        text1: [240, 236, 224],
        text2: [138, 128, 112],
        b: [40, 40, 45]
      };

      const W = 210, H = 297;
      
      doc.setFillColor(C.bg[0], C.bg[1], C.bg[2]);
      doc.rect(0, 0, W, H, 'F');

      doc.setFillColor(C.card[0], C.card[1], C.card[2]);
      doc.rect(0, 0, W, 25, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(C.gold[0], C.gold[1], C.gold[2]);
      doc.text('WORK TRACKER PRO', 15, 16);

      const periodLabel = period === '6months' ? '6-MONTH PERFORMANCE REPORT' : `ANNUAL REPORT ${viewDate.getFullYear()}`;
      doc.setFontSize(8);
      doc.setTextColor(C.text2[0], C.text2[1], C.text2[2]);
      doc.text(periodLabel, W - 15, 16, { align: 'right' });

      let y = 35;
      doc.setFillColor(C.card[0], C.card[1], C.card[2]);
      doc.roundedRect(15, y, W - 30, 40, 4, 4, 'F');
      
      doc.setFontSize(9);
      doc.setTextColor(C.gold[0], C.gold[1], C.gold[2]);
      doc.text('TOTAL EARNINGS', 22, y + 12);
      
      doc.setFontSize(32);
      doc.setTextColor(C.text1[0], C.text1[1], C.text1[2]);
      doc.text(`${curSym}${totalEarned.toLocaleString()}`, 22, y + 28);

      const miniStats = [
        { l: 'Days', v: totalDays },
        { l: 'Hours', v: `${totalHours}h` },
        { l: 'Goal', v: `${Math.round((totalEarned / (goal * (stats.length || 1))) * 100)}%` }
      ];
      
      miniStats.forEach((s, i) => {
        const sx = W - 25 - (2 - i) * 25;
        doc.setFontSize(14);
        doc.setTextColor(C.text1[0], C.text1[1], C.text1[2]);
        doc.text(String(s.v), sx, y + 22, { align: 'center' });
        doc.setFontSize(7);
        doc.setTextColor(C.text2[0], C.text2[1], C.text2[2]);
        doc.text(s.l, sx, y + 30, { align: 'center' });
      });

      y += 55;
      
      autoTable(doc, {
        startY: y,
        head: [['Month', 'Days', 'Hours', 'OT', 'Earned', 'Goal %']],
        body: stats.map(s => [s.label, s.days, `${s.hours}h`, `${s.otHours}h`, `${curSym}${formatMoney(s.earned, 0)}`, `${s.pct}%`]),
        theme: 'plain',
        styles: { fillColor: C.card, textColor: C.text1, fontSize: 8, cellPadding: 4 },
        headStyles: { fillColor: C.bg, textColor: C.gold, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [25, 25, 30] },
        margin: { left: 15, right: 15 }
      });

      if (totalDays > 0) {
        doc.addPage();
        doc.setFillColor(C.bg[0], C.bg[1], C.bg[2]);
        doc.rect(0, 0, W, H, 'F');
        
        doc.setFillColor(C.card[0], C.card[1], C.card[2]);
        doc.rect(0, 0, W, 20, 'F');
        
        doc.setFontSize(10);
        doc.setTextColor(C.gold[0], C.gold[1], C.gold[2]);
        doc.text('DAILY WORK LOG', 15, 13);
        
        const dayRows: any[] = [];
        stats.forEach(s => {
          s.entries.sort((a, b) => a.date.localeCompare(b.date)).forEach(e => {
            const isOT = e.hours > normal;
            dayRows.push([
              e.date,
              e.hours + 'h',
              isOT ? parseFloat((e.hours - normal).toFixed(1)) + 'h' : '-',
              curSym + formatMoney(calcEarnings(e.hours))
            ]);
          });
        });

        autoTable(doc, {
          startY: 25,
          head: [['Date', 'Hours', 'Overtime', 'Earned']],
          body: dayRows,
          theme: 'plain',
          styles: { fillColor: C.card, textColor: C.text1, fontSize: 7, cellPadding: 3 },
          headStyles: { fillColor: C.bg, textColor: C.gold, fontStyle: 'bold' },
          alternateRowStyles: { fillColor: [25, 25, 30] },
          margin: { left: 15, right: 15 }
        });
      }

      if (returnFile) {
        const blob = doc.output('blob');
        return new File([blob], `work-report-${period}-${now.toISOString().split('T')[0]}.pdf`, { type: 'application/pdf' });
      }

      doc.save(`work-report-${period}-${now.toISOString().split('T')[0]}.pdf`);
      addToast('PDF Exported Successfully', 'success');
    } catch (err) {
      console.error(err);
      if (!returnFile) addToast('PDF Export failed', 'error');
    } finally {
      if (!returnFile) setIsExporting(false);
    }
  };

  return {
    exportCSV,
    exportTXT,
    exportPDF,
    exportICS,
    shareToTelegram,
    shareBackup,
    isExporting
  };
};